# Site Settings
lang: en
title: Cosmic Horizons
tagline: A Space Mod never seen before 

description: >
  A Space Mod never seen before
baseurl: "/"
url: "https://cosmic-mod.github.io"
permalink: pretty
favicon: /assets/icon.jpg
#hide_share_buttons: true
theme_color: '#8c03fc'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr
force_theme: dark



plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass
  load_paths: 
     - node_modules



markdown: kramdown
highlighter: rouge

collections_dir:
collections:
  addonsupport:
    output: true
    folder: _addonsupport


  
